import "package:firebase_core/firebase_core.dart";

// Copy this file to firebase_config.dart and fill with real values
// generated by FlutterFire CLI for Android.
const FirebaseOptions firebaseOptions = FirebaseOptions(
  apiKey: "REPLACE_ME",
  appId: "REPLACE_ME",
  messagingSenderId: "REPLACE_ME",
  projectId: "REPLACE_ME",
  storageBucket: "REPLACE_ME",
);
